### ISSUE TITLE
[ERROR] Multiple packages found with the same name "robotino_msgs"

### ISSUE THREAD

**Issue by adbidwai** [eliabntt/active_v_slam#1]
Hello guys,
Thanks for open sourcing this work. I was trying to build the packages in this repository, but when I build it says it finds the `robotine_msgs` twice. So, I wanted to know which of the two `robotino_msgs` should I delete or remove? Is there any other way to resolve this issue? Following is the complete error log : 
```
 ✘ adbidwai@adbidwai-g3-3579  ~/catkin_ws  catkin build
-------------------------------------------------------------------------
Profile:                     default
Extending:          [cached] /home/adbidwai/nus_ws/devel:/opt/ros/melodic
Workspace:                   /home/adbidwai/catkin_ws
-------------------------------------------------------------------------
Build Space:        [exists] /home/adbidwai/catkin_ws/build
Devel Space:        [exists] /home/adbidwai/catkin_ws/devel
Install Space:      [unused] /home/adbidwai/catkin_ws/install
Log Space:          [exists] /home/adbidwai/catkin_ws/logs
Source Space:       [exists] /home/adbidwai/catkin_ws/src
DESTDIR:            [unused] None
-------------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
-------------------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
-------------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
-------------------------------------------------------------------------
Workspace configuration appears valid.
-------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/bin/catkin", line 11, in <module>
    load_entry_point('catkin-tools==0.6.1', 'console_scripts', 'catkin')()
  File "/usr/lib/python2.7/dist-packages/catkin_tools/commands/catkin.py", line 272, in main
    catkin_main(sysargs)
  File "/usr/lib/python2.7/dist-packages/catkin_tools/commands/catkin.py", line 267, in catkin_main
    sys.exit(args.main(args) or 0)
  File "/usr/lib/python2.7/dist-packages/catkin_tools/verbs/catkin_build/cli.py", line 422, in main
    summarize_build=opts.summarize  # Can be True, False, or None
  File "/usr/lib/python2.7/dist-packages/catkin_tools/verbs/catkin_build/build.py", line 283, in build_isolated_workspace
    workspace_packages = find_packages(context.source_space_abs, exclude_subspaces=True, warnings=[])
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 96, in find_packages
    raise RuntimeError('\n'.join(duplicates))
RuntimeError: Multiple packages found with the same name "robotino_msgs":
- active_v_slam/robotino_specific/robotino_msgs
- active_v_slam/src/robotino_msgs
```

TIA

**Comment by eliabntt** [comment]
Hi, I'm currently on holiday but it seems that you cloned everything inside the src folder in the catkin workspace. If that's the case you should try to change the folder structure. active_v_slam can be treated as a workspace but it's not a self contained package. Therefore, the src folder that you cloned should become the src folder of the workspace (i.e. ~/catkin_ws/src/active_slam). It's not clear now, I'll update the rreadme!thanks 😊

**Comment by adbidwai** [comment]
@eliabntt Oh right, yeah! That was such a silly mistake from my side. Thanks for your answer!

**Comment by eliabntt** [comment]
@adbidwai I'm back if you have any other issue/question please let me know😊
